name: Compilación automática

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Mostrar estructura del proyecto
        run: ls -R

      - name: Compilar codigo con Maven(Java)
        run: mvn compile
